version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
  backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      PORT: "3001"
      CORS_ORIGINS: "http://localhost:3000"
      CONFIG_ENCRYPTION_KEY: "local_dev_key_32_chars"
      JWT_SECRET: "local_dev_secret_64_chars"
      WEBAPP_ORIGIN: "http://localhost:3000"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ../apps/backend:/app
      - backenddata:/app/data
    depends_on: [ redis ]
    ports: [ "3001:3001" ]

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:3001"
    volumes:
      - ../apps/frontend:/app
    ports: [ "3000:3000" ]
    depends_on: [ backend ]

volumes:
  backenddata:
