global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ams-backend'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'ams-frontend'
    static_configs:
      - targets: ['frontend:8080']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s