name: CI-Frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Frontend-Abhängigkeiten installieren
        run: |
          cd auto-monetization-system/webapp
          npm install
      - name: Frontend-Build
        run: |
          cd auto-monetization-system/webapp
          npm run build
      - name: Docker Build Frontend
        run: |
          cd auto-monetization-system/webapp
          docker build -t ams-frontend .
