name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Backend-Abhängigkeiten installieren
        run: |
          cd auto-monetization-system/backend
          npm ci || npm install
      - name: Backend-Tests ausführen
        run: |
          cd auto-monetization-system/backend
          npm test --silent
      - name: Upload JUnit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-junit
          path: auto-monetization-system/backend/reports/*.xml
      - name: Docker Build Backend
        run: |
          cd auto-monetization-system/backend
          docker build -t ams-backend .
