
version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  redis:
    image: redis
    ports:
      - "6379:6379"
